name: yolov4-gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib==3.1.2
  - opencv
  - pip:
    - tensorflow-gpu==1.4.1
    - opencv-python==3.4.1
    - lxml
    - tqdm
    - absl-py==0.9.0
    - easydict
    - pillow==7.0.0
